In [3]:
import pandas as pd

import random

In [4]:
customer_data = []
for i in range(500):
    customer_id = random.randint(1001, 6000)
    age = random.randint(20, 65)
    gender = random.choice(["Male", "Female"])
    marital_status = random.choice(["Married", "Single", "Divorced"])
    annual_income = random.randint(30000, 120000)
    total_purchases = random.randint(10, 50)
    preferred_category = random.choice(["Electronics", "Appliances", "Home Goods"])
    customer_data.append([customer_id, age, gender, marital_status, annual_income, total_purchases, preferred_category])

print(customer_data)

[[4233, 60, 'Female', 'Single', 49819, 45, 'Home Goods'], [5451, 23, 'Male', 'Single', 37186, 13, 'Home Goods'], [5813, 40, 'Female', 'Married', 92643, 35, 'Electronics'], [3141, 57, 'Female', 'Married', 66103, 27, 'Home Goods'], [3121, 23, 'Female', 'Single', 40674, 25, 'Appliances'], [1025, 35, 'Male', 'Married', 30592, 29, 'Home Goods'], [5044, 21, 'Female', 'Single', 114518, 13, 'Appliances'], [2343, 60, 'Female', 'Single', 69676, 31, 'Appliances'], [1964, 20, 'Female', 'Single', 73393, 26, 'Appliances'], [4343, 59, 'Female', 'Divorced', 54515, 42, 'Electronics'], [1374, 39, 'Male', 'Single', 108051, 13, 'Appliances'], [5945, 45, 'Male', 'Single', 92664, 22, 'Home Goods'], [2744, 48, 'Female', 'Divorced', 53549, 40, 'Appliances'], [2446, 38, 'Male', 'Married', 81105, 44, 'Appliances'], [2225, 54, 'Male', 'Single', 61817, 20, 'Home Goods'], [1959, 25, 'Female', 'Married', 85097, 41, 'Appliances'], [4503, 34, 'Female', 'Divorced', 117419, 32, 'Electronics'], [2860, 58, 'Female', 'Single', 112414, 19, 'Electronics'], [5815, 22, 'Female', 'Married', 62413, 41, 'Home Goods'], [1207, 42, 'Female', 'Married', 57310, 43, 'Electronics'], [2045, 39, 'Male', 'Single', 90061, 15, 'Electronics'], [4587, 41, 'Female', 'Divorced', 36013, 42, 'Appliances'], [2536, 54, 'Female', 'Divorced', 97308, 22, 'Home Goods'], [5714, 62, 'Female', 'Divorced', 86230, 46, 'Home Goods'], [1344, 29, 'Female', 'Single', 74407, 39, 'Appliances'], [2448, 28, 'Male', 'Married', 37070, 33, 'Appliances'], [1952, 30, 'Female', 'Divorced', 51697, 23, 'Appliances'], [4678, 59, 'Male', 'Single', 36617, 44, 'Appliances'], [4960, 42, 'Female', 'Single', 76239, 15, 'Home Goods'], [4339, 63, 'Female', 'Married', 76395, 12, 'Appliances'], [1303, 60, 'Male', 'Married', 110409, 40, 'Appliances'], [3915, 63, 'Male', 'Single', 82602, 46, 'Appliances'], [2578, 28, 'Male', 'Divorced', 59410, 19, 'Appliances'], [2128, 32, 'Male', 'Single', 38341, 34, 'Electronics'], [4390, 49, 'Female', 'Divorced', 37997, 22, 'Appliances'], [2874, 36, 'Male', 'Single', 107464, 27, 'Appliances'], [3453, 44, 'Male', 'Divorced', 50370, 24, 'Appliances'], [4004, 47, 'Female', 'Married', 67248, 11, 'Appliances'], [5961, 39, 'Male', 'Single', 32480, 18, 'Electronics'], [3880, 56, 'Female', 'Single', 99012, 37, 'Electronics'], [1157, 49, 'Female', 'Single', 109163, 43, 'Appliances'], [2398, 20, 'Female', 'Single', 88768, 30, 'Home Goods'], [5439, 25, 'Male', 'Divorced', 47058, 46, 'Appliances'], [1601, 55, 'Female', 'Divorced', 72218, 18, 'Electronics'], [1316, 41, 'Male', 'Married', 35149, 47, 'Home Goods'], [2551, 44, 'Male', 'Married', 73766, 31, 'Appliances'], [2987, 27, 'Male', 'Single', 99862, 12, 'Home Goods'], [5042, 40, 'Male', 'Divorced', 111904, 41, 'Appliances'], [3939, 42, 'Male', 'Single', 53227, 45, 'Appliances'], [4554, 42, 'Female', 'Divorced', 116555, 46, 'Appliances'], [4757, 58, 'Female', 'Divorced', 99141, 30, 'Home Goods'], [2941, 53, 'Male', 'Married', 82476, 31, 'Home Goods'], [1318, 40, 'Female', 'Single', 47396, 22, 'Electronics'], [4431, 57, 'Male', 'Married', 40882, 19, 'Appliances'], [2230, 31, 'Male', 'Divorced', 113761, 40, 'Appliances'], [5163, 39, 'Male', 'Divorced', 60198, 21, 'Electronics'], [4009, 38, 'Female', 'Divorced', 104512, 34, 'Electronics'], [4332, 64, 'Female', 'Married', 84533, 21, 'Appliances'], [3235, 48, 'Female', 'Married', 76792, 19, 'Home Goods'], [5506, 53, 'Male', 'Single', 67578, 46, 'Appliances'], [3207, 23, 'Male', 'Single', 36351, 16, 'Appliances'], [4102, 65, 'Male', 'Single', 107106, 34, 'Appliances'], [4077, 40, 'Male', 'Divorced', 67435, 21, 'Electronics'], [3454, 37, 'Male', 'Single', 81555, 11, 'Appliances'], [4857, 54, 'Male', 'Divorced', 72427, 17, 'Appliances'], [3868, 27, 'Male', 'Divorced', 92473, 43, 'Appliances'], [3527, 20, 'Male', 'Divorced', 113592, 37, 'Appliances'], [5094, 62, 'Female', 'Married', 68582, 28, 'Appliances'], [4167, 43, 'Female', 'Single', 92409, 18, 'Home Goods'], [1181, 28, 'Male', 'Divorced', 73708, 47, 'Electronics'], [5694, 37, 'Female', 'Single', 62375, 48, 'Electronics'], [5582, 54, 'Female', 'Single', 84223, 36, 'Appliances'], [2215, 29, 'Female', 'Married', 59194, 34, 'Home Goods'], [5472, 20, 'Female', 'Married', 30974, 50, 'Electronics'], [4456, 47, 'Male', 'Divorced', 119294, 19, 'Electronics'], [1003, 48, 'Male', 'Married', 44225, 49, 'Appliances'], [4236, 38, 'Male', 'Married', 110822, 23, 'Home Goods'], [2966, 37, 'Male', 'Married', 66964, 43, 'Home Goods'], [3409, 52, 'Male', 'Divorced', 87694, 46, 'Appliances'], [4446, 54, 'Female', 'Divorced', 31405, 47, 'Electronics'], [4764, 44, 'Male', 'Single', 100124, 47, 'Home Goods'], [2982, 65, 'Male', 'Divorced', 46449, 11, 'Home Goods'], [1410, 36, 'Female', 'Single', 105740, 45, 'Electronics'], [3342, 64, 'Female', 'Divorced', 97312, 49, 'Appliances'], [2674, 26, 'Female', 'Divorced', 112888, 15, 'Appliances'], [3821, 30, 'Female', 'Single', 116301, 46, 'Appliances'], [2107, 56, 'Female', 'Divorced', 114733, 48, 'Home Goods'], [2258, 20, 'Female', 'Single', 80388, 49, 'Home Goods'], [3717, 58, 'Female', 'Married', 90343, 38, 'Appliances'], [1670, 50, 'Female', 'Single', 97270, 12, 'Electronics'], [3339, 30, 'Female', 'Divorced', 112431, 30, 'Home Goods'], [1655, 62, 'Female', 'Divorced', 105851, 46, 'Electronics'], [3192, 39, 'Female', 'Single', 87251, 19, 'Appliances'], [5167, 42, 'Male', 'Single', 43381, 28, 'Electronics'], [4896, 63, 'Male', 'Single', 96453, 19, 'Home Goods'], [3277, 44, 'Male', 'Married', 47152, 11, 'Home Goods'], [1697, 47, 'Male', 'Married', 96179, 22, 'Appliances'], [5206, 37, 'Female', 'Single', 75813, 37, 'Electronics'], [4023, 20, 'Female', 'Married', 108934, 44, 'Electronics'], [1195, 20, 'Female', 'Single', 57143, 46, 'Appliances'], [4325, 50, 'Female', 'Single', 79175, 31, 'Appliances'], [5505, 64, 'Female', 'Single', 93938, 26, 'Appliances'], [3066, 23, 'Female', 'Single', 91120, 12, 'Electronics'], [1227, 65, 'Male', 'Divorced', 109664, 50, 'Appliances'], [3625, 64, 'Male', 'Divorced', 99263, 13, 'Appliances'], [2303, 62, 'Female', 'Married', 33875, 12, 'Electronics'], [3954, 58, 'Male', 'Married', 47979, 26, 'Appliances'], [5909, 47, 'Male', 'Married', 78867, 13, 'Electronics'], [4887, 56, 'Female', 'Divorced', 48160, 20, 'Electronics'], [3891, 22, 'Female', 'Married', 114638, 16, 'Appliances'], [2633, 48, 'Female', 'Divorced', 45656, 38, 'Electronics'], [4929, 24, 'Female', 'Married', 30357, 44, 'Electronics'], [4320, 48, 'Male', 'Single', 33826, 46, 'Appliances'], [3866, 27, 'Male', 'Divorced', 65088, 11, 'Home Goods'], [3767, 51, 'Female', 'Divorced', 92588, 32, 'Appliances'], [5725, 21, 'Male', 'Single', 47432, 14, 'Electronics'], [3830, 55, 'Female', 'Married', 56890, 48, 'Home Goods'], [3326, 53, 'Female', 'Married', 39514, 42, 'Appliances'], [1730, 63, 'Male', 'Married', 116138, 44, 'Home Goods'], [5301, 44, 'Male', 'Single', 105318, 10, 'Electronics'], [2430, 45, 'Male', 'Single', 100276, 44, 'Home Goods'], [4611, 63, 'Female', 'Divorced', 97437, 29, 'Appliances'], [1921, 51, 'Male', 'Divorced', 88740, 34, 'Home Goods'], [1293, 51, 'Female', 'Divorced', 46392, 21, 'Electronics'], [3793, 61, 'Male', 'Single', 32654, 40, 'Home Goods'], [4203, 61, 'Female', 'Divorced', 93832, 26, 'Appliances'], [5701, 57, 'Female', 'Divorced', 90637, 34, 'Home Goods'], [3590, 50, 'Male', 'Married', 61610, 25, 'Home Goods'], [4986, 35, 'Male', 'Divorced', 54851, 31, 'Electronics'], [1407, 59, 'Male', 'Single', 64017, 50, 'Electronics'], [4824, 29, 'Female', 'Single', 56073, 43, 'Home Goods'], [2799, 61, 'Female', 'Married', 37041, 21, 'Electronics'], [5310, 34, 'Male', 'Married', 87507, 34, 'Electronics'], [2742, 28, 'Female', 'Divorced', 89626, 16, 'Electronics'], [4079, 27, 'Female', 'Married', 96861, 43, 'Home Goods'], [2156, 27, 'Female', 'Divorced', 107567, 35, 'Electronics'], [5966, 57, 'Male', 'Single', 72923, 45, 'Electronics'], [1050, 22, 'Male', 'Married', 85262, 50, 'Home Goods'], [4838, 45, 'Male', 'Single', 96076, 20, 'Home Goods'], [4937, 56, 'Female', 'Single', 103182, 45, 'Appliances'], [2932, 46, 'Female', 'Single', 67127, 12, 'Appliances'], [1568, 64, 'Male', 'Married', 98680, 25, 'Home Goods'], [4816, 60, 'Female', 'Single', 102825, 50, 'Appliances'], [4959, 47, 'Male', 'Married', 60334, 46, 'Home Goods'], [4680, 54, 'Male', 'Married', 60199, 33, 'Home Goods'], [3060, 28, 'Female', 'Married', 100250, 21, 'Appliances'], [1607, 50, 'Female', 'Single', 79166, 33, 'Electronics'], [5270, 64, 'Male', 'Divorced', 117821, 50, 'Appliances'], [3428, 49, 'Male', 'Married', 88824, 43, 'Home Goods'], [4301, 45, 'Male', 'Married', 85285, 24, 'Appliances'], [2864, 62, 'Male', 'Single', 32167, 12, 'Appliances'], [3610, 44, 'Female', 'Married', 67263, 13, 'Home Goods'], [4476, 34, 'Male', 'Married', 39766, 42, 'Home Goods'], [3122, 63, 'Male', 'Single', 96953, 39, 'Home Goods'], [5674, 48, 'Female', 'Married', 99404, 15, 'Appliances'], [3559, 33, 'Male', 'Divorced', 89117, 27, 'Home Goods'], [3779, 37, 'Female', 'Married', 104748, 36, 'Appliances'], [5337, 50, 'Female', 'Single', 107301, 30, 'Electronics'], [5165, 23, 'Male', 'Married', 71536, 18, 'Electronics'], [3556, 20, 'Male', 'Divorced', 114656, 18, 'Home Goods'], [4163, 29, 'Female', 'Single', 32252, 45, 'Home Goods'], [3086, 37, 'Male', 'Single', 83367, 46, 'Home Goods'], [1776, 30, 'Female', 'Divorced', 62580, 48, 'Electronics'], [3548, 45, 'Male', 'Divorced', 68931, 43, 'Home Goods'], [1196, 37, 'Male', 'Divorced', 63591, 22, 'Home Goods'], [1055, 49, 'Female', 'Divorced', 64840, 50, 'Appliances'], [3608, 32, 'Female', 'Single', 116059, 46, 'Electronics'], [1372, 20, 'Male', 'Single', 36558, 34, 'Appliances'], [2386, 23, 'Female', 'Single', 94617, 41, 'Electronics'], [1438, 45, 'Female', 'Single', 117738, 23, 'Home Goods'], [5359, 21, 'Male', 'Divorced', 67006, 30, 'Appliances'], [4880, 51, 'Male', 'Married', 63799, 45, 'Home Goods'], [4742, 65, 'Female', 'Single', 116461, 21, 'Appliances'], [2930, 30, 'Female', 'Single', 81666, 35, 'Appliances'], [2653, 28, 'Female', 'Married', 105332, 47, 'Home Goods'], [4301, 63, 'Female', 'Single', 67015, 12, 'Home Goods'], [4255, 42, 'Female', 'Single', 51420, 27, 'Home Goods'], [4308, 64, 'Male', 'Married', 111373, 38, 'Electronics'], [3903, 38, 'Male', 'Single', 91759, 29, 'Electronics'], [2649, 60, 'Male', 'Divorced', 75311, 29, 'Appliances'], [1235, 21, 'Female', 'Divorced', 95090, 18, 'Appliances'], [5930, 58, 'Female', 'Divorced', 36385, 46, 'Appliances'], [2248, 29, 'Male', 'Divorced', 58803, 23, 'Home Goods'], [3455, 34, 'Female', 'Married', 33547, 20, 'Home Goods'], [3756, 50, 'Female', 'Married', 108051, 48, 'Electronics'], [3651, 28, 'Male', 'Divorced', 105240, 41, 'Electronics'], [3888, 39, 'Female', 'Divorced', 64514, 47, 'Electronics'], [1668, 47, 'Female', 'Married', 97630, 31, 'Appliances'], [5902, 47, 'Male', 'Single', 100849, 26, 'Home Goods'], [4699, 41, 'Female', 'Divorced', 117474, 26, 'Appliances'], [2330, 55, 'Male', 'Married', 113855, 17, 'Home Goods'], [2810, 63, 'Female', 'Married', 98809, 34, 'Electronics'], [4630, 53, 'Male', 'Married', 84764, 30, 'Appliances'], [3874, 52, 'Male', 'Single', 48568, 42, 'Home Goods'], [4798, 20, 'Male', 'Divorced', 37634, 21, 'Home Goods'], [5616, 31, 'Male', 'Married', 40709, 20, 'Home Goods'], [1888, 48, 'Male', 'Divorced', 103755, 19, 'Home Goods'], [1715, 24, 'Male', 'Single', 60178, 14, 'Home Goods'], [4654, 25, 'Female', 'Married', 56836, 12, 'Appliances'], [4750, 62, 'Female', 'Single', 64426, 10, 'Home Goods'], [2866, 48, 'Female', 'Divorced', 109325, 26, 'Appliances'], [5183, 36, 'Male', 'Single', 44995, 35, 'Home Goods'], [3843, 54, 'Female', 'Single', 46599, 12, 'Home Goods'], [3763, 50, 'Female', 'Single', 116443, 13, 'Appliances'], [2631, 58, 'Female', 'Single', 45424, 42, 'Electronics'], [5354, 22, 'Male', 'Single', 109675, 44, 'Appliances'], [1756, 30, 'Female', 'Divorced', 110358, 28, 'Home Goods'], [2881, 20, 'Male', 'Divorced', 101700, 34, 'Home Goods'], [1591, 41, 'Female', 'Divorced', 32270, 17, 'Electronics'], [1522, 59, 'Female', 'Married', 35627, 22, 'Appliances'], [2110, 33, 'Female', 'Single', 83565, 47, 'Appliances'], [4468, 29, 'Female', 'Married', 32878, 11, 'Home Goods'], [3281, 53, 'Female', 'Married', 45997, 29, 'Electronics'], [1445, 46, 'Female', 'Married', 107083, 39, 'Electronics'], [4925, 33, 'Male', 'Married', 58355, 19, 'Electronics'], [5237, 22, 'Male', 'Single', 105430, 42, 'Electronics'], [1357, 36, 'Female', 'Single', 30150, 14, 'Appliances'], [3158, 60, 'Male', 'Divorced', 53536, 35, 'Home Goods'], [4005, 34, 'Female', 'Married', 76211, 41, 'Electronics'], [2749, 50, 'Male', 'Single', 75560, 12, 'Electronics'], [2361, 35, 'Male', 'Married', 66252, 13, 'Home Goods'], [3722, 28, 'Female', 'Single', 79252, 35, 'Home Goods'], [4451, 65, 'Female', 'Married', 87344, 10, 'Electronics'], [3683, 43, 'Female', 'Divorced', 91998, 32, 'Electronics'], [4244, 59, 'Male', 'Divorced', 43985, 21, 'Electronics'], [3168, 32, 'Female', 'Single', 109367, 45, 'Home Goods'], [4727, 30, 'Female', 'Married', 70004, 28, 'Electronics'], [5582, 62, 'Male', 'Divorced', 85265, 49, 'Appliances'], [1993, 39, 'Male', 'Single', 114006, 33, 'Appliances'], [4623, 37, 'Male', 'Single', 106566, 43, 'Home Goods'], [2899, 61, 'Female', 'Married', 76317, 38, 'Appliances'], [3686, 38, 'Female', 'Married', 41556, 37, 'Home Goods'], [2156, 43, 'Male', 'Single', 67100, 21, 'Appliances'], [3314, 60, 'Male', 'Divorced', 90846, 27, 'Appliances'], [4680, 55, 'Female', 'Married', 70369, 41, 'Home Goods'], [5188, 38, 'Female', 'Divorced', 81659, 21, 'Appliances'], [1076, 58, 'Female', 'Divorced', 71645, 23, 'Electronics'], [3065, 22, 'Male', 'Divorced', 110986, 27, 'Appliances'], [5041, 28, 'Male', 'Married', 119903, 43, 'Home Goods'], [4758, 51, 'Female', 'Single', 47493, 38, 'Appliances'], [2678, 40, 'Male', 'Divorced', 38120, 45, 'Appliances'], [4058, 39, 'Male', 'Single', 39190, 18, 'Electronics'], [2652, 41, 'Female', 'Single', 97474, 19, 'Appliances'], [4649, 40, 'Female', 'Divorced', 59551, 32, 'Home Goods'], [1593, 57, 'Male', 'Divorced', 55340, 11, 'Appliances'], [5769, 22, 'Female', 'Divorced', 67612, 23, 'Home Goods'], [3793, 34, 'Male', 'Divorced', 42317, 46, 'Home Goods'], [1942, 44, 'Female', 'Married', 57023, 12, 'Home Goods'], [4425, 44, 'Male', 'Divorced', 31392, 20, 'Electronics'], [5453, 22, 'Male', 'Divorced', 46377, 23, 'Home Goods'], [5060, 61, 'Female', 'Married', 92001, 23, 'Home Goods'], [1343, 54, 'Male', 'Single', 118703, 10, 'Appliances'], [2517, 39, 'Male', 'Single', 99811, 31, 'Appliances'], [2608, 57, 'Male', 'Single', 42849, 44, 'Appliances'], [4211, 64, 'Male', 'Single', 119319, 20, 'Home Goods'], [1565, 49, 'Female', 'Divorced', 85254, 43, 'Electronics'], [2601, 65, 'Male', 'Divorced', 87976, 50, 'Appliances'], [4280, 22, 'Male', 'Divorced', 32341, 28, 'Electronics'], [3908, 57, 'Female', 'Single', 78265, 35, 'Home Goods'], [4965, 28, 'Male', 'Divorced', 86958, 19, 'Electronics'], [3021, 24, 'Male', 'Divorced', 102162, 12, 'Appliances'], [3999, 61, 'Female', 'Single', 115505, 47, 'Electronics'], [1061, 45, 'Female', 'Single', 97340, 30, 'Home Goods'], [1249, 44, 'Male', 'Single', 46987, 23, 'Appliances'], [4492, 34, 'Female', 'Single', 73607, 34, 'Home Goods'], [1241, 39, 'Male', 'Married', 37444, 50, 'Electronics'], [4567, 38, 'Male', 'Divorced', 73030, 33, 'Appliances'], [2459, 63, 'Male', 'Divorced', 102905, 49, 'Home Goods'], [1933, 30, 'Female', 'Divorced', 68810, 41, 'Electronics'], [3186, 53, 'Male', 'Divorced', 52454, 40, 'Electronics'], [3602, 40, 'Male', 'Divorced', 40475, 23, 'Electronics'], [1751, 37, 'Male', 'Divorced', 116522, 49, 'Home Goods'], [2746, 20, 'Male', 'Divorced', 33633, 27, 'Appliances'], [4937, 39, 'Male', 'Single', 66886, 43, 'Appliances'], [5898, 52, 'Female', 'Married', 37563, 38, 'Electronics'], [1540, 55, 'Female', 'Single', 110774, 29, 'Appliances'], [1525, 25, 'Female', 'Married', 35783, 49, 'Home Goods'], [4964, 58, 'Female', 'Single', 108867, 24, 'Appliances'], [2035, 32, 'Female', 'Married', 113527, 17, 'Appliances'], [3333, 63, 'Female', 'Divorced', 113782, 20, 'Appliances'], [2243, 27, 'Female', 'Single', 116267, 50, 'Appliances'], [3310, 41, 'Male', 'Single', 83819, 26, 'Appliances'], [4236, 35, 'Male', 'Single', 79529, 12, 'Electronics'], [5510, 45, 'Male', 'Divorced', 74833, 28, 'Electronics'], [1516, 53, 'Female', 'Divorced', 97818, 25, 'Home Goods'], [1018, 48, 'Male', 'Divorced', 114438, 16, 'Appliances'], [3917, 55, 'Female', 'Single', 61949, 19, 'Home Goods'], [1372, 59, 'Female', 'Married', 99048, 15, 'Electronics'], [5611, 49, 'Female', 'Single', 91824, 22, 'Appliances'], [3107, 52, 'Male', 'Single', 78827, 22, 'Home Goods'], [2749, 60, 'Female', 'Single', 74056, 10, 'Home Goods'], [3927, 52, 'Female', 'Married', 63817, 43, 'Appliances'], [3861, 55, 'Male', 'Married', 96459, 41, 'Electronics'], [3992, 53, 'Female', 'Single', 89981, 47, 'Home Goods'], [1937, 41, 'Female', 'Married', 45865, 20, 'Electronics'], [1182, 47, 'Female', 'Divorced', 81165, 18, 'Appliances'], [5067, 37, 'Male', 'Divorced', 89243, 25, 'Appliances'], [4132, 33, 'Female', 'Single', 72646, 14, 'Appliances'], [4204, 36, 'Male', 'Divorced', 42510, 42, 'Electronics'], [5700, 39, 'Female', 'Married', 83359, 28, 'Electronics'], [4482, 36, 'Male', 'Divorced', 93418, 27, 'Appliances'], [4018, 63, 'Male', 'Married', 92009, 14, 'Appliances'], [5401, 22, 'Female', 'Married', 32175, 49, 'Electronics'], [3803, 61, 'Female', 'Divorced', 98225, 49, 'Home Goods'], [5381, 39, 'Female', 'Married', 49811, 37, 'Home Goods'], [4585, 35, 'Female', 'Married', 76111, 27, 'Appliances'], [3701, 56, 'Female', 'Married', 91180, 10, 'Appliances'], [5020, 31, 'Male', 'Married', 115888, 34, 'Electronics'], [1944, 31, 'Male', 'Single', 67345, 31, 'Home Goods'], [3958, 31, 'Male', 'Divorced', 54698, 45, 'Electronics'], [4640, 25, 'Female', 'Divorced', 116705, 29, 'Appliances'], [4685, 28, 'Male', 'Divorced', 63868, 17, 'Electronics'], [3934, 51, 'Female', 'Married', 36426, 13, 'Electronics'], [4654, 29, 'Male', 'Single', 59110, 37, 'Appliances'], [1204, 39, 'Female', 'Married', 53084, 13, 'Electronics'], [2007, 56, 'Male', 'Divorced', 109831, 43, 'Home Goods'], [5740, 25, 'Female', 'Single', 41165, 40, 'Home Goods'], [4166, 51, 'Male', 'Married', 95501, 17, 'Home Goods'], [3076, 44, 'Female', 'Divorced', 40954, 41, 'Home Goods'], [5306, 23, 'Female', 'Married', 39398, 33, 'Appliances'], [4311, 42, 'Female', 'Divorced', 47449, 45, 'Electronics'], [3533, 38, 'Male', 'Divorced', 99109, 13, 'Electronics'], [5069, 20, 'Female', 'Single', 92854, 44, 'Electronics'], [3880, 58, 'Male', 'Divorced', 82213, 23, 'Electronics'], [4614, 59, 'Female', 'Single', 31104, 40, 'Electronics'], [2060, 49, 'Male', 'Divorced', 77686, 34, 'Electronics'], [2377, 50, 'Male', 'Divorced', 39233, 46, 'Appliances'], [2029, 48, 'Female', 'Married', 79448, 30, 'Electronics'], [5705, 56, 'Male', 'Married', 68938, 36, 'Home Goods'], [5355, 45, 'Female', 'Divorced', 36506, 34, 'Home Goods'], [1308, 25, 'Male', 'Married', 74802, 48, 'Home Goods'], [4541, 24, 'Female', 'Married', 105645, 23, 'Home Goods'], [5932, 43, 'Female', 'Divorced', 104455, 11, 'Appliances'], [1827, 53, 'Male', 'Married', 113338, 50, 'Appliances'], [4251, 36, 'Female', 'Divorced', 96036, 23, 'Home Goods'], [2498, 52, 'Female', 'Single', 40397, 11, 'Home Goods'], [3411, 61, 'Female', 'Divorced', 86342, 27, 'Home Goods'], [5090, 24, 'Female', 'Married', 114466, 22, 'Home Goods'], [1599, 42, 'Female', 'Divorced', 79594, 11, 'Home Goods'], [5700, 65, 'Female', 'Divorced', 98166, 12, 'Electronics'], [5032, 64, 'Male', 'Single', 31338, 28, 'Appliances'], [1027, 22, 'Male', 'Divorced', 79095, 31, 'Electronics'], [5256, 44, 'Female', 'Single', 57827, 30, 'Home Goods'], [1206, 34, 'Male', 'Single', 105355, 25, 'Appliances'], [1467, 51, 'Male', 'Divorced', 56174, 45, 'Appliances'], [4580, 48, 'Female', 'Single', 101091, 39, 'Home Goods'], [2943, 46, 'Male', 'Divorced', 89656, 15, 'Appliances'], [2361, 53, 'Male', 'Mar

In [5]:
dataset=pd.DataFrame(customer_data)
dataset

        0   1       2         3       4   5            6
0    4233  60  Female    Single   49819  45   Home Goods
1    5451  23    Male    Single   37186  13   Home Goods
2    5813  40  Female   Married   92643  35  Electronics
3    3141  57  Female   Married   66103  27   Home Goods
4    3121  23  Female    Single   40674  25   Appliances
..    ...  ..     ...       ...     ...  ..          ...
495  4813  60  Female  Divorced  116508  16   Home Goods
496  3620  36    Male   Married   60423  24  Electronics
497  2738  55  Female  Divorced   52191  37  Electronics
498  2616  29    Male   Married   93230  11   Home Goods
499  3795  48    Male   Married   55045  44  Electronics

[500 rows x 7 columns]

In [6]:
dataset.columns=['customer_id','age', 'gender', 'marital_status', 'annual_income', 'total_purchases', 'preferred_category']
dataset

,customer_id,age,gender,marital_status,annual_income,total_purchases,preferred_category
0,4233,60,Female,Single,49819,45,Home Goods
1,5451,23,Male,Single,37186,13,Home Goods
2,5813,40,Female,Married,92643,35,Electronics
3,3141,57,Female,Married,66103,27,Home Goods
4,3121,23,Female,Single,40674,25,Appliances
...,...,...,...,...,...,...,...
495,4813,60,Female,Divorced,116508,16,Home Goods
496,3620,36,Male,Married,60423,24,Electronics
497,2738,55,Female,Divorced,52191,37,Electronics
498,2616,29,Male,Married,93230,11,Home Goods
499,3795,48,Male,Married,55045,44,Electronics

In [7]:
dataset.to_csv('Customer_Dataset.csv')